### ISSUE TITLE
imageurl: Opening Playlists at Dashboard

### ISSUE THREAD

**Issue by davinbirdi** [turing-club/electron-spotify#8]
Initially when I press the refresh button all my playlists show up fine, but when I click on one I do not get any actions. With Amy, on her setup she would be able to click a playlist and it would proceed to the songlist, but with the same code (ensured I pulled and merged) I could not get the same outcome. 

I played around and when I comment in line 43 of `home.js` of the function `loadPlaylist()` :
`var imageurl;// = data.images[0].url;`
I am able to click the playlist and proceed to the playlist list.

**Comment by cadrianxyz** [comment]
Attempted to fix issue by adding default images for playlists and songs!
