### ISSUE TITLE
backend: API Access Token expired on re-login

### ISSUE THREAD

**Issue by davinbirdi** [turing-club/electron-spotify#9]
After closing the server and electron and restarting everything, when I login with an already created account I get these HTTP errors:

On the frontend console:
```
GET http://127.0.0.1:8000/api/get-playlists?user_id=18 500 (Internal Server Error)
send @ jquery-3.4.1.js:9837
ajax @ jquery-3.4.1.js:9434
(anonymous) @ home.js:191
```

and on the backend:
```
The access token expired
[02/Sep/2019 19:50:36] "GET /api/get-playlists?user_id=18 HTTP/1.1" 500 99331
```
Currently I just make a new account and it prompts me to the spotify login window where I accept giving our app access to my Spotify account.

**Comment by bf777** [comment]
@cezzzanne could you look into developing a token refresh mechanism to address this?
